=== Prajwal2001532/WebStack2022/stu.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="College">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SID" type="xs:integer" />
              <xs:element name="Sname" type="xs:string" />
              <xs:element name="Scourse" type="xs:string" />
              <xs:element name="Ssem" type="xs:integer" />
              <xs:element name="Sage" type="xs:integer" />
              <xs:element name="sub1">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="100" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="sub2">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="100" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="sub3">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:minInclusive value="0" />
                    <xs:maxInclusive value="100" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Total" type="xs:string" />
              <xs:element name="Average" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Prajwal2001532/WebStack2022/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="stu.xsl" type="text/xsl"?>
<College  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="stu.xsd">
    <student>
        <SID>1</SID>
        <Sname>Prajwal</Sname>
        <Scourse>MCA</Scourse>
        <Ssem>1</Ssem>
        <sub1>100</sub1>
        <sub2>100</sub2>
        <sub3>100</sub3>
        <Total>300</Total>
        <Average>100</Average>
    </student>
    <student>
        <SID>2</SID>
        <Sname>Bhoomika</Sname>
        <Scourse>Btech</Scourse>
        <Ssem>6</Ssem>
        <sub1>100</sub1>
        <sub2>100</sub2>
        <sub3>100</sub3>
        <Total>289</Total>
        <Average>80</Average>
    </student>
    <student>
        <SID>3</SID>
        <Sname>Raj</Sname>
        <Scourse>BCA</Scourse>
        <Ssem>5</Ssem>
        <sub1>80</sub1>
        <sub2>90</sub2>
        <sub3>80</sub3>
        <Total>278</Total>
        <Average>93</Average>
    </student>
   
</College>
